name: Security checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 2 1 * *' # Runs on the first day of every month at 2:30 AM

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    name: Cargo Audit
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run cargo audit
        run: cargo audit

  clippy:
    name: Cargo Clippy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run clippy
        run: cargo clippy -- -D warnings
